#!/bin/bash

mysql -e 'drop   database wallsdb'
mysql -e 'create database wallsdb'

mysql wallsdb < doc/regions.sql 
mysql wallsdb < doc/provinces.sql 
mysql wallsdb < doc/walls.mysql 

rake db:schema:dump
touch tmp/restart.txt

mysql wallsdb -e "insert into users values (0, 'Luca Sisalli', 'luca@gmail.com', NULL)"

mysql wallsdb << EOF
insert into \`walls\` (\`id\`, \`lat\`, \`lng\`, \`name\`, \`description\`, \`address\`, \`cap\`, \`city\`, \`province_id\`, \`web\`) values 
                      (1,44.5148233,11.3593858, 'Eden Climbing - OZ Bologna', 
                       '<p>Arrampicare! <i>... Parlare di scalata in termini di piacere può sembrare strano; eppure, è di questo che si tratta.  A tutte le età e a qualunque grado di pratica, i massi e le falesie procurano dei piaceri profondi e a diversi livelli: padroneggiare armoniosamente il corpo, imparare a vincere il dubbio, tentare di superare se stessi... o, ancora, dividere un momento di amicizia!
</i><br/>
Patrick Edlinger.
</p>

<p>
Questo è lo spirito che accomuna il gruppo di Eden Climbing, non solo una struttura di arrampicata per migliorare il proprio livello ma soprattutto un luogo dove condividere la propria passione.
</p>',
                      'Via Staligrado, 59', 40126, 'Bologna', 14,
                      'http://www.ozbologna.org/eden-park/eden-climbing/'),
                     (2, 37.5257713,15.0706357, 'C.U.S Catania', 
                      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                      'Via Pippo Pluto, 123', NULL, 'Catania', 23,
                      'http://www.cuscatania.it/'),
                    (3, 45.4979508,9.1697593, 'Passaggio Obbligato', 
                     'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                     'Via degli Imbriani, 17', NULL, 'Milano', 57,
                     'http://www.passaggiobbligato.it/'),
                    (4, 45.4540707,9.2499973, 'Rock Sport Asd', 
                     'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                     'Via Gaudenzio Fantoli, 15/1', NULL, 'Milano', 57,
                     'http://www.rockspot.it/'),
                    (5, 45.4050137,11.0196173, 'King Rock', 
                     'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                     'Via Cà Mazzè, 21', NULL, 'Verona',  107,
                     'http://www.kingrock.it/'),
                    (6, 44.5811892,10.9320114, 'Equilibrium Scsd', 
                     'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                     'Via Tincani Martelli, 140', NULL, 'Portile di Modena', 58,
                     'http://www.equilibriumarrampicata.it'),
                    (7, 41.8537869,12.3810073, 'GET UP!', 
                     'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                     'Via Vincenzo Statella, 19', '00149', 'Roma', 85,
                     'http://www.getupasd.it'),
                    (8, 41.8935934,12.4677782, 'Rock it Climbing Roma', 
                     'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                     'Via Biordo Michelotti, 17', '00176', 'Roma', 85,
                     'http://www.rockit-arrampicataroma.it'),
                    (9, 43.1040582,12.3610691, 'Arrampicata Libera A.s.d. - Metropolitan Boulder', 
                     'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                     'Piazzale Umbria Jazz 1/e', '06125', 'Perugia', 70,
                     'https://www.facebook.com/pages/Metropolitan-Boulder/655217164498659'),
                    (10, 44.5039231,11.4041635, 'UP Urban Climbing', 
                     'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                     'Via del Fonditore, 1', '40138', 'Bologna', 14,
                     'http://www.upurbanclimbing.it/'), 
                    (11, 44.476834,11.420544, "Monkeys' Planet a.s.d.", 
                     'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                     'Via Vittoria, 23A', '40068', 'San Lazzaro di Savena',  14,
                     'http://monkeysplanet.altervista.org');
                     



EOF

mysql wallsdb << EOF
update walls set `boulder_mq` = 100 where id=1;
update walls set `boulder_notes` = "Pareti appogiate, verticali e strapiombanti fino a 40 gradi." where id=1;
update walls set `training` = "1 trave, 2 pan Gullich, Trx, spalliere etc etc." where id=1;
update walls set `bar`      = "Birre e spritz da mani professionali." where id=1;
update walls set `music`    = "Sempre" where id=1;

EOF


